### ISSUE TITLE
Roadmap/Potential Additions

### ISSUE THREAD

**Issue by mkayeterry** [mkayeterry/recipe-urls#3]
- Allow for html as an input - [recipe-scrapers scrape_html](https://github.com/hhursev/recipe-scrapers/blob/d0f6d9af61fa82f327a069489d72067e3708bb11/recipe_scrapers/__init__.py#L683)
- Return dictionary or set of compatible sites - {‘allrecipes’: ‘www.allrecipes.com’}
    - It might be nice to know what sites are covered without having to check the README
- Proxy and header arguments
- Consider if there a way around hardcoded [unwanted_patterns](https://github.com/mkayeterry/recipe-urls/blob/7466bcc123ee4d66f0171b67fa547254d4f4706b/recipe_urls/ambitiouskitchen.py#L24)

These are some short term plans for moving forward, but I'm very open to ideas/suggestions! @jknndy

**Comment by jknndy** [comment]
- [x] Consider switching to `requests` for site retrieval
- [x] Expand testing base, related to adding html as an input.
- [ ] Generate file to pre-create all files / etc when adding new coverage
- [ ] Adopt `black` formatting for all .py files
- [ ] Set up merge pytests / tox
